# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 585)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.activecontour = QtWidgets.QTabWidget(self.centralwidget)
        self.activecontour.setEnabled(True)
        self.activecontour.setGeometry(QtCore.QRect(0, 0, 889, 551))
        self.activecontour.setAutoFillBackground(True)
        self.activecontour.setObjectName("activecontour")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.label_filters_input = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_input.setGeometry(QtCore.QRect(180, 30, 331, 231))
        self.label_filters_input.setAutoFillBackground(True)
        self.label_filters_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_input.setScaledContents(True)
        self.label_filters_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_input.setObjectName("label_filters_input")
        self.label_filters_output = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_output.setGeometry(QtCore.QRect(520, 30, 331, 231))
        self.label_filters_output.setAutoFillBackground(True)
        self.label_filters_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_filters_output.setScaledContents(True)
        self.label_filters_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_output.setObjectName("label_filters_output")
        self.pushButton_filters_load = QtWidgets.QPushButton(self.tab_filters)
        self.pushButton_filters_load.setGeometry(QtCore.QRect(20, 30, 121, 81))
        self.pushButton_filters_load.setObjectName("pushButton_filters_load")
        self.label = QtWidgets.QLabel(self.tab_filters)
        self.label.setGeometry(QtCore.QRect(30, 140, 41, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_filters)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 31, 21))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_filters)
        self.groupBox.setGeometry(QtCore.QRect(30, 300, 751, 111))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 30, 311, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 152, 39))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 20, 41, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 311, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_filters)
        self.lineEdit.setGeometry(QtCore.QRect(70, 140, 101, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_filters)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 190, 51, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_36 = QtWidgets.QLabel(self.tab_filters)
        self.label_36.setGeometry(QtCore.QRect(20, 450, 741, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_filters)
        self.label_37.setGeometry(QtCore.QRect(420, 450, 541, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.activecontour.addTab(self.tab_filters, "")
        self.tab_histograms = QtWidgets.QWidget()
        self.tab_histograms.setObjectName("tab_histograms")
        self.pushButton_histograms_load = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_histograms_load.setGeometry(QtCore.QRect(40, 20, 121, 81))
        self.pushButton_histograms_load.setObjectName("pushButton_histograms_load")
        self.label_histograms_input = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_input.setGeometry(QtCore.QRect(171, 20, 241, 201))
        self.label_histograms_input.setAutoFillBackground(True)
        self.label_histograms_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input.setScaledContents(True)
        self.label_histograms_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input.setObjectName("label_histograms_input")
        self.label_histograms_output = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_output.setGeometry(QtCore.QRect(421, 20, 261, 201))
        self.label_histograms_output.setAutoFillBackground(True)
        self.label_histograms_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output.setScaledContents(True)
        self.label_histograms_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output.setObjectName("label_histograms_output")
        self.label_10 = QtWidgets.QLabel(self.tab_histograms)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 71, 21))
        self.label_10.setObjectName("label_10")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_histograms)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 150, 91, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_histograms)
        self.comboBox_7.setGeometry(QtCore.QRect(700, 20, 131, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_histograms)
        self.comboBox_8.setGeometry(QtCore.QRect(700, 240, 121, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.setItemText(3, "")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_histograms)
        self.comboBox_9.setGeometry(QtCore.QRect(10, 210, 141, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.output_histogram = PlotWidget(self.tab_histograms)
        self.output_histogram.setGeometry(QtCore.QRect(421, 246, 261, 261))
        self.output_histogram.setAutoFillBackground(True)
        self.output_histogram.setObjectName("output_histogram")
        self.input_histogram = PlotWidget(self.tab_histograms)
        self.input_histogram.setGeometry(QtCore.QRect(169, 246, 241, 261))
        self.input_histogram.setAutoFillBackground(True)
        self.input_histogram.setObjectName("input_histogram")
        self.label_6 = QtWidgets.QLabel(self.tab_histograms)
        self.label_6.setGeometry(QtCore.QRect(431, 230, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_26 = QtWidgets.QLabel(self.tab_histograms)
        self.label_26.setGeometry(QtCore.QRect(179, 230, 81, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_histograms)
        self.label_27.setGeometry(QtCore.QRect(700, 110, 91, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_histograms)
        self.label_28.setGeometry(QtCore.QRect(690, 160, 121, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_histograms)
        self.lineEdit_9.setGeometry(QtCore.QRect(820, 100, 41, 41))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_29 = QtWidgets.QLabel(self.tab_histograms)
        self.label_29.setGeometry(QtCore.QRect(700, 70, 141, 16))
        self.label_29.setObjectName("label_29")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_histograms)
        self.lineEdit_10.setGeometry(QtCore.QRect(820, 150, 41, 41))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_38 = QtWidgets.QLabel(self.tab_histograms)
        self.label_38.setGeometry(QtCore.QRect(710, 300, 161, 41))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_histograms)
        self.label_39.setGeometry(QtCore.QRect(770, 330, 121, 20))
        self.label_39.setObjectName("label_39")
        self.activecontour.addTab(self.tab_histograms, "")
        self.tab_hybrid = QtWidgets.QWidget()
        self.tab_hybrid.setObjectName("tab_hybrid")
        self.label_histograms_input_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_input_2.setGeometry(QtCore.QRect(180, 20, 241, 211))
        self.label_histograms_input_2.setAutoFillBackground(True)
        self.label_histograms_input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input_2.setScaledContents(True)
        self.label_histograms_input_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input_2.setObjectName("label_histograms_input_2")
        self.label_histograms_hinput_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_hinput_2.setGeometry(QtCore.QRect(180, 250, 241, 231))
        self.label_histograms_hinput_2.setAutoFillBackground(True)
        self.label_histograms_hinput_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_2.setScaledContents(True)
        self.label_histograms_hinput_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_2.setObjectName("label_histograms_hinput_2")
        self.label_histograms_output_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_output_2.setGeometry(QtCore.QRect(430, 20, 431, 461))
        self.label_histograms_output_2.setAutoFillBackground(True)
        self.label_histograms_output_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output_2.setScaledContents(True)
        self.label_histograms_output_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output_2.setObjectName("label_histograms_output_2")
        self.label_12 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 71, 21))
        self.label_12.setObjectName("label_12")
        self.pushButton_histograms_load_2 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_2.setGeometry(QtCore.QRect(20, 20, 121, 81))
        self.pushButton_histograms_load_2.setObjectName("pushButton_histograms_load_2")
        self.label_13 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_13.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_14.setGeometry(QtCore.QRect(30, 310, 71, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_15.setGeometry(QtCore.QRect(30, 290, 71, 21))
        self.label_15.setObjectName("label_15")
        self.pushButton_histograms_load_3 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_3.setGeometry(QtCore.QRect(20, 200, 121, 81))
        self.pushButton_histograms_load_3.setObjectName("pushButton_histograms_load_3")
        self.pushButton_histograms_load_4 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_4.setGeometry(QtCore.QRect(20, 350, 121, 41))
        self.pushButton_histograms_load_4.setObjectName("pushButton_histograms_load_4")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_hybrid)
        self.lineEdit_11.setGeometry(QtCore.QRect(60, 130, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_hybrid)
        self.lineEdit_12.setGeometry(QtCore.QRect(60, 310, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.activecontour.addTab(self.tab_hybrid, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(20, 200, 31, 21))
        self.label_23.setObjectName("label_23")
        self.pushButton_Hough_load = QtWidgets.QPushButton(self.tab)
        self.pushButton_Hough_load.setGeometry(QtCore.QRect(10, 60, 121, 81))
        self.pushButton_Hough_load.setObjectName("pushButton_Hough_load")
        self.lineEdit_size_Hough = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_size_Hough.setGeometry(QtCore.QRect(60, 192, 81, 31))
        self.lineEdit_size_Hough.setObjectName("lineEdit_size_Hough")
        self.label_Hough_output = QtWidgets.QLabel(self.tab)
        self.label_Hough_output.setGeometry(QtCore.QRect(510, 30, 331, 200))
        self.label_Hough_output.setAutoFillBackground(True)
        self.label_Hough_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Hough_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_Hough_output.setScaledContents(True)
        self.label_Hough_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Hough_output.setObjectName("label_Hough_output")
        self.label_Hough_input = QtWidgets.QLabel(self.tab)
        self.label_Hough_input.setGeometry(QtCore.QRect(170, 30, 331, 200))
        self.label_Hough_input.setAutoFillBackground(True)
        self.label_Hough_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Hough_input.setScaledContents(True)
        self.label_Hough_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Hough_input.setObjectName("label_Hough_input")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 290, 471, 151))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 181, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.comboBox_shape = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.comboBox_shape.setObjectName("comboBox_shape")
        self.comboBox_shape.addItem("")
        self.comboBox_shape.addItem("")
        self.comboBox_shape.addItem("")
        self.comboBox_shape.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_shape)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(200, 20, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(211, 360, 152, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_mask_size = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_mask_size.setGeometry(QtCore.QRect(351, 360, 51, 31))
        self.lineEdit_mask_size.setObjectName("lineEdit_mask_size")
        self.label_Hough_output_2 = QtWidgets.QLabel(self.tab)
        self.label_Hough_output_2.setGeometry(QtCore.QRect(510, 240, 331, 200))
        self.label_Hough_output_2.setAutoFillBackground(True)
        self.label_Hough_output_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Hough_output_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_Hough_output_2.setScaledContents(True)
        self.label_Hough_output_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Hough_output_2.setObjectName("label_Hough_output_2")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(550, 460, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_opencv = QtWidgets.QPushButton(self.tab)
        self.pushButton_opencv.setGeometry(QtCore.QRect(690, 460, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_opencv.setFont(font)
        self.pushButton_opencv.setObjectName("pushButton_opencv")
        self.pushButton_apply_hough = QtWidgets.QPushButton(self.tab)
        self.pushButton_apply_hough.setGeometry(QtCore.QRect(150, 240, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_apply_hough.setFont(font)
        self.pushButton_apply_hough.setObjectName("pushButton_apply_hough")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(60, 470, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.activecontour.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_Harris_output = QtWidgets.QLabel(self.tab_3)
        self.label_Harris_output.setGeometry(QtCore.QRect(510, 30, 331, 231))
        self.label_Harris_output.setAutoFillBackground(True)
        self.label_Harris_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Harris_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_Harris_output.setScaledContents(True)
        self.label_Harris_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Harris_output.setObjectName("label_Harris_output")
        self.pushButton_Harris_load = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Harris_load.setGeometry(QtCore.QRect(10, 30, 121, 81))
        self.pushButton_Harris_load.setObjectName("pushButton_Harris_load")
        self.lineEdit_size_Harris = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_size_Harris.setGeometry(QtCore.QRect(60, 160, 81, 31))
        self.lineEdit_size_Harris.setObjectName("lineEdit_size_Harris")
        self.label_Harris_input = QtWidgets.QLabel(self.tab_3)
        self.label_Harris_input.setGeometry(QtCore.QRect(170, 30, 331, 231))
        self.label_Harris_input.setAutoFillBackground(True)
        self.label_Harris_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Harris_input.setScaledContents(True)
        self.label_Harris_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Harris_input.setObjectName("label_Harris_input")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(210, 320, 421, 191))
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(40, 24, 311, 141))
        self.groupBox_9.setObjectName("groupBox_9")
        self.ratio = QtWidgets.QLineEdit(self.groupBox_9)
        self.ratio.setGeometry(QtCore.QRect(120, 98, 61, 20))
        self.ratio.setText("")
        self.ratio.setObjectName("ratio")
        self.label_32 = QtWidgets.QLabel(self.groupBox_9)
        self.label_32.setGeometry(QtCore.QRect(36, 98, 71, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_9)
        self.label_33.setGeometry(QtCore.QRect(40, 40, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_40 = QtWidgets.QLabel(self.tab_3)
        self.label_40.setGeometry(QtCore.QRect(20, 160, 31, 21))
        self.label_40.setObjectName("label_40")
        self.Harris_ApplyButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.Harris_ApplyButton_2.setGeometry(QtCore.QRect(20, 240, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Harris_ApplyButton_2.setFont(font)
        self.Harris_ApplyButton_2.setObjectName("Harris_ApplyButton_2")
        self.activecontour.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_size_snake = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_size_snake.setGeometry(QtCore.QRect(60, 130, 81, 21))
        self.lineEdit_size_snake.setObjectName("lineEdit_size_snake")
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setGeometry(QtCore.QRect(20, 130, 31, 21))
        self.label_41.setObjectName("label_41")
        self.label_snake_output = QtWidgets.QLabel(self.tab_2)
        self.label_snake_output.setGeometry(QtCore.QRect(510, 30, 331, 231))
        self.label_snake_output.setAutoFillBackground(True)
        self.label_snake_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_snake_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_snake_output.setScaledContents(True)
        self.label_snake_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_snake_output.setObjectName("label_snake_output")
        self.label_snake_input = QtWidgets.QLabel(self.tab_2)
        self.label_snake_input.setGeometry(QtCore.QRect(170, 30, 331, 231))
        self.label_snake_input.setAutoFillBackground(True)
        self.label_snake_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_snake_input.setScaledContents(True)
        self.label_snake_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_snake_input.setObjectName("label_snake_input")
        self.pushButton_snake_load = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_snake_load.setGeometry(QtCore.QRect(10, 20, 121, 81))
        self.pushButton_snake_load.setObjectName("pushButton_snake_load")
        self.snake_apply = QtWidgets.QPushButton(self.tab_2)
        self.snake_apply.setGeometry(QtCore.QRect(20, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.snake_apply.setFont(font)
        self.snake_apply.setObjectName("snake_apply")
        self.Reset = QtWidgets.QPushButton(self.tab_2)
        self.Reset.setGeometry(QtCore.QRect(20, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Reset.setFont(font)
        self.Reset.setObjectName("Reset")
        self.clear_anchors = QtWidgets.QPushButton(self.tab_2)
        self.clear_anchors.setGeometry(QtCore.QRect(20, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_anchors.setFont(font)
        self.clear_anchors.setObjectName("clear_anchors")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 431, 121))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(40, 40, 91, 21))
        self.label_9.setObjectName("label_9")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(40, 70, 71, 39))
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(50, 60, 51, 21))
        self.label_16.setObjectName("label_16")
        self.lineEdit_alpha = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_alpha.setGeometry(QtCore.QRect(100, 40, 61, 20))
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.lineEdit_gamma = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_gamma.setGeometry(QtCore.QRect(100, 80, 61, 20))
        self.lineEdit_gamma.setObjectName("lineEdit_gamma")
        self.lineEdit_beta = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_beta.setGeometry(QtCore.QRect(100, 60, 61, 20))
        self.lineEdit_beta.setObjectName("lineEdit_beta")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(210, 20, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(190, 40, 231, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(10, 453, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_snake_output_running = QtWidgets.QLabel(self.tab_2)
        self.label_snake_output_running.setGeometry(QtCore.QRect(510, 300, 331, 221))
        self.label_snake_output_running.setAutoFillBackground(True)
        self.label_snake_output_running.setFrameShape(QtWidgets.QFrame.Box)
        self.label_snake_output_running.setTextFormat(QtCore.Qt.PlainText)
        self.label_snake_output_running.setScaledContents(True)
        self.label_snake_output_running.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_snake_output_running.setObjectName("label_snake_output_running")
        self.lineEdit_iteration_num = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_iteration_num.setGeometry(QtCore.QRect(735, 270, 41, 20))
        self.lineEdit_iteration_num.setObjectName("lineEdit_iteration_num")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(625, 269, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(515, 269, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(140, 10, 711, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(150, 453, 221, 20))
        self.label_30.setObjectName("label_30")
        self.lineEdit_chain_code = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_chain_code.setGeometry(QtCore.QRect(12, 480, 481, 41))
        self.lineEdit_chain_code.setObjectName("lineEdit_chain_code")
        self.lineEdit_Perimeter_of_contour = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Perimeter_of_contour.setGeometry(QtCore.QRect(100, 420, 113, 20))
        self.lineEdit_Perimeter_of_contour.setObjectName("lineEdit_Perimeter_of_contour")
        self.lineEdit_area_of_contour = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_area_of_contour.setGeometry(QtCore.QRect(280, 420, 113, 20))
        self.lineEdit_area_of_contour.setObjectName("lineEdit_area_of_contour")
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setGeometry(QtCore.QRect(30, 420, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setGeometry(QtCore.QRect(240, 420, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.activecontour.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.activecontour.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_filters_input.setText(_translate("MainWindow", "Input image"))
        self.label_filters_output.setText(_translate("MainWindow", "Output image"))
        self.pushButton_filters_load.setText(_translate("MainWindow", "Load Image"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Size:"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter Settings"))
        self.label_3.setText(_translate("MainWindow", "       Add noise"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Select"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Uniform"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Salt-papper"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Additional Parameters"))
        self.label_5.setText(_translate("MainWindow", "                          Mask size"))
        self.label_4.setText(_translate("MainWindow", "      Select Filter"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "Select"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Select"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Mean"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Median"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Sobel"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Roberts"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Prewitt"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Canny"))
        self.label_36.setText(_translate("MainWindow", "Waiting......Result image can take few seconds "))
        self.label_37.setText(_translate("MainWindow", "(until name of selected filter appear in combox)"))
        self.activecontour.setTabText(self.activecontour.indexOf(self.tab_filters), _translate("MainWindow", "Filters"))
        self.pushButton_histograms_load.setText(_translate("MainWindow", "Load image"))
        self.label_histograms_input.setText(_translate("MainWindow", "Input image"))
        self.label_histograms_output.setText(_translate("MainWindow", "Output image"))
        self.label_10.setText(_translate("MainWindow", "Size:"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Select Effect to  image "))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Normalize"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Equalize "))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Global Thresholding "))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Local Thresholding"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Select curve "))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Cumlative curve "))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "distribution curve"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "select color of histogram"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Red"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "Green "))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "Blue "))
        self.label_6.setText(_translate("MainWindow", "output histogram"))
        self.label_26.setText(_translate("MainWindow", "input histogram"))
        self.label_27.setText(_translate("MainWindow", "Enter size window"))
        self.label_28.setText(_translate("MainWindow", "Enter threshold or ratio"))
        self.label_29.setText(_translate("MainWindow", "For Thresholding "))
        self.label_38.setText(_translate("MainWindow", "note that distribution curve :"))
        self.label_39.setText(_translate("MainWindow", "will appear in consol"))
        self.activecontour.setTabText(self.activecontour.indexOf(self.tab_histograms), _translate("MainWindow", "Histograms"))
        self.label_histograms_input_2.setText(_translate("MainWindow", "Input image A"))
        self.label_histograms_hinput_2.setText(_translate("MainWindow", "Input image B"))
        self.label_histograms_output_2.setText(_translate("MainWindow", "Output image"))
        self.label_12.setText(_translate("MainWindow", "Name:"))
        self.pushButton_histograms_load_2.setText(_translate("MainWindow", "Load image A"))
        self.label_13.setText(_translate("MainWindow", "Size:"))
        self.label_14.setText(_translate("MainWindow", "Size:"))
        self.label_15.setText(_translate("MainWindow", "Name:"))
        self.pushButton_histograms_load_3.setText(_translate("MainWindow", "Load image B"))
        self.pushButton_histograms_load_4.setText(_translate("MainWindow", "Make Hybrid"))
        self.activecontour.setTabText(self.activecontour.indexOf(self.tab_hybrid), _translate("MainWindow", "Hybrid"))
        self.label_23.setText(_translate("MainWindow", "Size:"))
        self.pushButton_Hough_load.setText(_translate("MainWindow", "Load Image"))
        self.label_Hough_output.setText(_translate("MainWindow", "Output image"))
        self.label_Hough_input.setText(_translate("MainWindow", "Input image"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Operator  Settings"))
        self.label_25.setText(_translate("MainWindow", "   Select shapes"))
        self.comboBox_shape.setCurrentText(_translate("MainWindow", "select"))
        self.comboBox_shape.setItemText(0, _translate("MainWindow", "select"))
        self.comboBox_shape.setItemText(1, _translate("MainWindow", "Lines"))
        self.comboBox_shape.setItemText(2, _translate("MainWindow", "Circles"))
        self.comboBox_shape.setItemText(3, _translate("MainWindow", "Canny"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Circles and Canny Parameters"))
        self.label_7.setText(_translate("MainWindow", "                          Mask size"))
        self.label_Hough_output_2.setText(_translate("MainWindow", "Output image2"))
        self.label_8.setText(_translate("MainWindow", "canny using opencv"))
        self.pushButton_opencv.setText(_translate("MainWindow", "Apply"))
        self.pushButton_apply_hough.setText(_translate("MainWindow", "Apply"))
        self.label_31.setText(_translate("MainWindow", "Waiting .....Result image can take few seconds"))
        self.activecontour.setTabText(self.activecontour.indexOf(self.tab), _translate("MainWindow", "Hough"))
        self.label_Harris_output.setText(_translate("MainWindow", "Output image"))
        self.pushButton_Harris_load.setText(_translate("MainWindow", "Load Image"))
        self.label_Harris_input.setText(_translate("MainWindow", "Input image"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Operator  Settings"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Detector  Tunable Parameters"))
        self.label_32.setText(_translate("MainWindow", "threshold ratio"))
        self.label_33.setText(_translate("MainWindow", "for better result be in range :0.01  :  0.05"))
        self.label_40.setText(_translate("MainWindow", "Size:"))
        self.Harris_ApplyButton_2.setText(_translate("MainWindow", "Apply"))
        self.activecontour.setTabText(self.activecontour.indexOf(self.tab_3), _translate("MainWindow", "Harris"))
        self.label_41.setText(_translate("MainWindow", "Size:"))
        self.label_snake_output.setText(_translate("MainWindow", "Output image"))
        self.label_snake_input.setText(_translate("MainWindow", "input image "))
        self.pushButton_snake_load.setText(_translate("MainWindow", "Load Image"))
        self.snake_apply.setText(_translate("MainWindow", "Apply"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.clear_anchors.setText(_translate("MainWindow", "Clear Anchors "))
        self.label_11.setText(_translate("MainWindow", "contour setting "))
        self.label_9.setText(_translate("MainWindow", "  Alpha    "))
        self.label_17.setText(_translate("MainWindow", "  Gamma"))
        self.label_16.setText(_translate("MainWindow", "Beta"))
        self.label_21.setText(_translate("MainWindow", "For  Better result try "))
        self.label_22.setWhatsThis(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">&quot; alpha=0.015, beta=10, gamma=0.001&quot;</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "\" alpha=0.015, beta=10, gamma=0.001\""))
        self.label_18.setText(_translate("MainWindow", "chain code for contour   "))
        self.label_snake_output_running.setText(_translate("MainWindow", "Output image snake ruuning "))
        self.label_19.setText(_translate("MainWindow", "Iteration Num"))
        self.label_20.setText(_translate("MainWindow", "Running snake,"))
        self.label_24.setText(_translate("MainWindow", "click only 2 points : 1st point is center of circle & 2nd point for identify reduis of circle (contain object)"))
        self.label_30.setText(_translate("MainWindow", "(scroll right or left to show all chain code )"))
        self.label_34.setText(_translate("MainWindow", "Perimeter"))
        self.label_35.setText(_translate("MainWindow", "Area"))
        self.activecontour.setTabText(self.activecontour.indexOf(self.tab_2), _translate("MainWindow", "Active Contour "))

from pyqtgraph import PlotWidget
